// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWnebGEFOSVNcb9ND5qs6J1ZahqB8Dj3A',
    appId: '1:365079309712:web:2a48ea24cc0bc443851715',
    messagingSenderId: '365079309712',
    projectId: 'crypto-wallet-b9bb2',
    authDomain: 'crypto-wallet-b9bb2.firebaseapp.com',
    storageBucket: 'crypto-wallet-b9bb2.appspot.com',
    measurementId: 'G-JKNPG4728J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpVFueOm8Gl8CQScN5IAtS6PpQEpYsF_k',
    appId: '1:365079309712:android:ef29464928e791b3851715',
    messagingSenderId: '365079309712',
    projectId: 'crypto-wallet-b9bb2',
    storageBucket: 'crypto-wallet-b9bb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBw5xe5EH140Zt999ee37GbTjSJlf31Rc',
    appId: '1:365079309712:ios:9cd3471331fd7665851715',
    messagingSenderId: '365079309712',
    projectId: 'crypto-wallet-b9bb2',
    storageBucket: 'crypto-wallet-b9bb2.appspot.com',
    iosClientId: '365079309712-or7gminru3qmucofdgvd4jakq746qr3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.teacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBw5xe5EH140Zt999ee37GbTjSJlf31Rc',
    appId: '1:365079309712:ios:9cd3471331fd7665851715',
    messagingSenderId: '365079309712',
    projectId: 'crypto-wallet-b9bb2',
    storageBucket: 'crypto-wallet-b9bb2.appspot.com',
    iosClientId: '365079309712-or7gminru3qmucofdgvd4jakq746qr3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.teacher',
  );
}
